language: python
python:
 - '3.5'
 - '3.6'
 - '3.7'
env:
 - TOX_ENV=py35
 - TOX_ENV=py36
 - TOX_ENV=py37
install:
 - pip install requirements_dev.txt
before_script:
 - coverage erase
script:
 - tox -e $TOX_ENV
after_success:
 - coveralls